<div class="fieldset-wrapper" id="add-products-to-category-wrapper">
    <fieldset class="fieldset" id="add-products-to-category-wrapper-group-fields">
        <legend class="legend">
            <span><?=  __("Remove the additional images") ?></span>
        </legend>
        <br>
        <div class="fields">
            <input name="remove_additional_images"
                   class="checkbox category-checkbox"
                   id="remove_additional_images"
                   type="checkbox" />
            <label for="remove_additional_images">
                Remove Additional/Gallery Images From Selected Products
            </label>
        </div>
    </fieldset>
</div>