<div class="fieldset-wrapper" id="add-products-to-category-wrapper">
    <fieldset class="fieldset" id="add-products-to-category-wrapper-group-fields">
        <legend class="legend">
            <span><?=  __("Remove images") ?></span>
        </legend>
        <br>
        <p>Please note this may be a slow operation and should be separately to other changes</p>
        <p><strong>Make a database backup before running</strong></p>
        <div class="fields">
            <div class="admin__field field">
                <label class="label admin__field-label">
                    <span data-config-scope="[GLOBAL]">Remove Base Images</span>
                </label>
                <div>
                    <input name="remove_base_images" class="checkbox" type="checkbox">
                </div>
            </div>
            <div class="admin__field field">
                <label class="label admin__field-label">
                    <span data-config-scope="[GLOBAL]">Remove Small Images</span>
                </label>
                <div>
                    <input name="remove_small_images" class="checkbox" type="checkbox">
                </div>
            </div>
            <div class="admin__field field">
                <label class="label admin__field-label">
                    <span data-config-scope="[GLOBAL]">Remove thumbnail Images</span>
                </label>
                <div>
                    <input name="remove_thumbnail_images" class="checkbox" type="checkbox">
                </div>
            </div>
            <div class="admin__field field">
                <label class="label admin__field-label">
                    <span data-config-scope="[GLOBAL]">Remove Additional/Gallery Images</span>
                </label>
                <div>
                    <input name="remove_additional_images" class="checkbox" type="checkbox">
                </div>
            </div>
<!--            <div class="field">-->
<!--                <input name="remove_base_images"-->
<!--                       class="checkbox category-checkbox"-->
<!--                       id="remove_base_images"-->
<!--                       type="checkbox" />-->
<!--                <label for="remove_base_images">-->
<!--                    [global] Remove Base Images-->
<!--                </label>-->
<!--            </div>-->
<!--            <div class="field">-->
<!--                <input name="remove_small_images"-->
<!--                       class="checkbox category-checkbox"-->
<!--                       id="remove_small_images"-->
<!--                       type="checkbox" />-->
<!--                <label for="remove_small_images">-->
<!--                    [global] Remove Small Images-->
<!--                </label>-->
<!--            </div>-->
<!--            <div class="field">-->
<!--                <input name="remove_thumbnail_images"-->
<!--                       class="checkbox category-checkbox"-->
<!--                       id="remove_thumbnail_images"-->
<!--                       type="checkbox" />-->
<!--                <label for="remove_thumbnail_images">-->
<!--                    [global] Remove thumbnail Images-->
<!--                </label>-->
<!--            </div>-->
<!--            <div class="field">-->
<!--                <input name="remove_additional_images"-->
<!--                       class="checkbox category-checkbox"-->
<!--                       id="remove_additional_images"-->
<!--                       type="checkbox" />-->
<!--                <label for="remove_additional_images">-->
<!--                    [global] Remove Additional/Gallery Images-->
<!--                </label>-->
<!--            </div>-->
        </div>
    </fieldset>
</div>
